<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>name</key>
		<string>Mustache</string>
		<key>fileTypes</key>
		<array>
			<string>mustache</string>
		</array>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>text.html.basic</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>text.html.mustache</string>
	</dict>
</plist>
